apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: webapp
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream auth-service {
            server auth-service:3001;
        }
        upstream user-service {
            server user-service:3002;
        }
        upstream product-service {
            server product-service:3003;
        }
        upstream order-service {
            server order-service:3004;
        }
        server {
            listen 80;
            server_name localhost;
            
            location /api/auth/ {
                proxy_pass http://auth-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/users/ {
                proxy_pass http://user-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/products/ {
                proxy_pass http://product-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/orders/ {
                proxy_pass http://order-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location / {
                return 404;
            }
        }
    }