apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: webapp
  labels:
    app: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: authdb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: password
        volumeMounts:
        - name: postgres-auth-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -h 127.0.0.1 -U $POSTGRES_USER
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -h 127.0.0.1 -U $POSTGRES_USER
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgres-auth-storage
        persistentVolumeClaim:
          claimName: postgres-auth-pvc