apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: webapp
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004