apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: webapp
spec:
  selector:
    app: postgres-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None