apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: webapp
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003