apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: webapp
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002